### ISSUE TITLE
maybe test against private discord server and slack workspace?

### ISSUE THREAD

**Issue by ed1621** [jimboslicethat/discordinated-slacking#1]
i have a channel and workspace we can work off of

discord: 
https://discord.gg/WGHYxjE

slack: 
https://join.slack.com/t/taco-sandbox/shared_invite/zt-clls8qs2-PzunOR0P11_jUw32ZLO8pw

**Comment by BuiltByWalsh** [comment]
Really good idea. Not sure how much you've looked at the setup yet, but this would just be a matter of updating our `.env` ENV vars to reference the correct slack webhook url and we would also need a new bot in the test discord and along with a token we could use for the `Discord.Client`.

**Comment by BuiltByWalsh** [comment]
You want to take a stab at getting the slack bot & discord bot made in these test servers/workspaces? Once you've tested and verified I can change my setup to reference the correct secrets. @ed1621

**Comment by ed1621** [comment]
Got bots set up in a private slack and discord server for testing
